name: Smoke Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
    - name: capture target from branch
      run: |
        echo "Running smoke tests..."
        apt-get update -y && DEBIAN_FRONTEND=noninteractive apt install -y wget sudo software-properties-common curl tzdata
        export USER=$(whoami)  # Explicitly set the USER environment variable
        sudo wget -q https://raw.githubusercontent.com/vigneshsubbaram/dotfiles/refs/heads/main/bootstrap_ubuntu_wsl.sh -O - | bash
        echo "Smoke tests completed successfully."