tools_dir:  ~/.local/bin

platforms:
  linux:
    - amd64

tools:
  kubectx:
    repo: ahmetb/kubectx
    asset_patterns:
      linux: kubectx

  kubens:
    repo: ahmetb/kubectx
    asset_patterns:
      linux: kubens

  bosh:
    repo: cloudfoundry/bosh-cli

  helmfile:
    repo: helmfile/helmfile

  cf:
    repo: cloudfoundry/cli
    tag: v6.53.0

  k9s:
    repo: derailed/k9s

  credhub:
    repo: cloudfoundry/credhub-cli

  cue:
    repo: cue-lang/cue

  df-pv:
    repo: yashbhutwala/kubectl-df-pv

  fly:
    repo: concourse/concourse
    asset_patterns:
      linux: fly-{version}-linux-amd64.tgz

  hugo:
    repo: gohugoio/hugo
    asset_patterns:
      linux: hugo_extended_{version}_linux-amd64.tar.gz

  istioctl:
    repo: istio/istio
    asset_patterns:
      linux: istioctl-{version}-linux-amd64.tar.gz

  kapp:
    repo: carvel-dev/kapp

  vela:
    repo: kubevela/kubevela
    asset_patterns:
      linux: vela-v{version}-linux-amd64.tar.gz
    tag: v1.9.5

  yq:
    repo: mikefarah/yq

  ytt:
    repo: carvel-dev/ytt

  delta:
    repo: dandavison/delta

  fd: sharkdp/fd

  bat:
    repo: sharkdp/bat

  eza:
    repo: eza-community/eza

  fzf:
    repo: junegunn/fzf

  rg:
    repo: BurntSushi/ripgrep

  act:
    repo: nektos/act

  cilium:
    repo: cilium/cilium-cli

  opa:
    repo: open-policy-agent/opa
    tag: v0.58.0

  regal:
    repo: StyraInc/regal
    tag: v0.18.0

  task:
    repo: go-task/task

  flux:
    repo: fluxcd/flux2
    tag: v2.5.0

  k3d:
    repo: k3d-io/k3d

  chainsaw:
    repo: kyverno/chainsaw

  clusterawsadm:
    repo: kubernetes-sigs/cluster-api-provider-aws

  packer-plugin-goss:
    repo: YaleUniversity/packer-plugin-goss
    path_in_archive: packer-plugin-goss_v3.2.14_x5.0_linux_amd64

  mustache:
    repo: quantumew/mustache-cli

  nvim:
    repo: neovim/neovim

  ruff:
    repo: astral-sh/ruff
    asset_patterns:
      linux: ruff-x86_64-unknown-linux-gnu.tar.gz

  kind:
    repo: kubernetes-sigs/kind

  clusterctl:
    repo: kubernetes-sigs/cluster-api
    asset_patterns:
      linux: clusterctl-linux-amd64
    extract_archive: false
    binary_name: clusterctl

  velero:
    repo: vmware-tanzu/velero

  krew:
    repo: kubernetes-sigs/krew
    asset_patterns:
      linux: krew-linux_amd64.tar.gz
    binary_name: krew
    path_in_archive: krew-linux_amd64

  cli:
    repo: cli/cli
    binary_name: gh
